Running self-installer...    ERR_PNPM_UNSUPPORTED_ENGINE  Unsupported environment (bad pnpm and/or Node.js version)
  This error happened while installing a direct dependency of /home/runner/setup-pnpm

  Your Node version is incompatible with "registry.npmjs.org/pnpm/11.0.9".

  Expected version: >=22.13
  Got: v20.20.2

  This is happening because the package's manifest has an engines.node field specified.
  To fix this issue, install the required Node version.
Error: Something went wrong, self-installer exits with code 1